name = "BiodiversityObservationNetworks"
uuid = "a5b868d3-191d-4bba-a38a-ad28190da010"
authors = ["michael catchen <michael.catchen@colorado.edu>"]
version = "0.4.0"

[deps]
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
DelaunayTriangulation = "927a84f5-c5f4-47a5-9785-b46e178433df"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeometryOps = "3251bfac-6a57-4b6d-aa61-ac1fef2975ab"
HaltonSequences = "13907d55-377f-55d6-a9d6-25ac19e11b95"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SliceMap = "82cb661a-3f19-5665-9e27-df437c7e54c8"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
SpeciesDistributionToolkit = "72b53823-5c0b-4575-ad0e-8e97227ad13b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
BONsMakieExt = "Makie"

[compat]
Clustering = "0.15.7"
DelaunayTriangulation = "1.6.3"
Distances = "0.10.12"
Distributions = "0.25"
GeoInterface = "1.4.0"
GeometryOps = "0.1.13"
HaltonSequences = "0.2"
HiGHS = "1.5"
JuMP = "1.11"
LinearAlgebra = "1.11"
MultivariateStats = "0.10.3"
ProgressMeter = "1.7.2"
SliceMap = "0.2.7"
SpecialFunctions = "2.1"
SpeciesDistributionToolkit = "1.2.0"
Statistics = "1.11.0"
StatsBase = "0.34"
Term = "2.0.0"
Random = "1.11"
julia = "1.11"
