[deps]
BiodiversityObservationNetworks = "a5b868d3-191d-4bba-a38a-ad28190da010"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
NeutralLandscapes = "71847384-8354-4223-ac08-659a5128069f"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
SimpleSDMPolygons = "dd4c243c-bc7b-45f6-b2b3-6bd128d3a12b"
SpeciesDistributionToolkit = "72b53823-5c0b-4575-ad0e-8e97227ad13b"
